version: "3"
services:
  db:
    image: postgres:latest
    networks:
      - hmpps
    container_name: contacts-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contacts-db
      POSTGRES_USER: contacts
      POSTGRES_PASSWORD: contacts

networks:
  hmpps:
