spring:
  flyway:
    # This should be removed when we think the DB is stable, and we should be moving onto migrations for changes.
    # The spring profile "dbclean" is set in the values-dev.yaml file, so it only applies to the DEV db.
    clean-disabled: false
    clean-on-validation-error: true